/***********FUNCIONES DE SEÑALES*************/
void Pulsado(GtkWidget *Widget, gpointer data);
void Abrir_menu_juego (GtkToolButton *toolbutton, gpointer data);
void MenuGuardar(GtkWidget *Widget, gpointer data);
void MenuAbrir(GtkWidget *Widget, gpointer data);
void Manual(GtkWidget *Widget, gpointer data);
void TerminarPartida(GtkWidget *Widget, gpointer data);
void IniciarPartida(GtkWidget *Widget, gpointer data);
void Esconder(GtkWidget *Widget, gpointer data);
void Esconder2(GtkWidget *Widget, gpointer data);
void Esconder3(GtkWidget *Widget, gpointer data);
void Esconder4(GtkWidget *Widget, gpointer data);
void Esconder5(GtkWidget *Widget, gpointer data);
void EsconderVentana(GtkWidget *Widget, gpointer data);
void CerrarJuego(GtkWidget *Widget, gpointer data);
gboolean CerrarJuego1(GtkWidget *Widget, GdkEvent *event, gpointer data);
void CerrarJuego2(GtkWidget *Widget, gpointer data);
void Acerca_de(GtkWidget *Widget, gpointer data);
void RecorreHistorial(GtkWidget *Widget, gpointer data);
void on_button_clicked(GtkWidget *Widget, gpointer data);
void SeguirAMano(GtkWidget *Widget, gpointer data);
